apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: frontend
  name: frontend
spec:
  replicas: 10
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - image: httpd:alpine3.18
          name: httpd
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1      # Specifies the maximum number of Pods that can be created over the desired number of Pods during the update.
      maxUnavailable: 1    # Specifies the maximum number of Pods that can be unavailable during the update
