apiVersion: v1
kind: Service
metadata:
  name: my-service
  labels:
    app: frontend
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
  type: LoadBalancer

